// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Home_Scr.h"
#include "screens/ui_Alarm_Scr.h"
#include "screens/ui_Sketchpad_Scr.h"
#include "screens/ui_Alarm_Ringing_Scr.h"
#include "screens/ui_Color_Scr.h"
#include "screens/ui_Settings_Scr.h"
#include "screens/ui_Whats_Down.h"
#include "screens/ui_MamaKontakt.h"
#include "screens/ui_TataKontakt.h"
#include "screens/ui_PrimljenePoruke.h"
#include "screens/ui_Zivotinje.h"
#include "screens/ui_PogodiKojaJeZivotinja.h"
#include "screens/ui_TocanOdgovor.h"
#include "screens/ui_KriviOdgovor.h"
#include "screens/ui_Camera_Scr.h"
#include "screens/ui_Gallery_Scr.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * SpinAndLargen_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * LargeBtn_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * MoveColorToCenter_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * MoveSettingsToCenter_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * HideBtn_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * ShowBtn_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_colorwheel_icon_png);   // assets/colorwheel_icon.png
LV_IMG_DECLARE( ui_img_bl_logo_symbol_png);   // assets/bl_logo_symbol.png
LV_IMG_DECLARE( ui_img_settings_icon_png);   // assets/settings_icon.png
LV_IMG_DECLARE( ui_img_sketchpad_icon_png);   // assets/sketchpad_icon.png
LV_IMG_DECLARE( ui_img_alarm_icon_png);   // assets/alarm_icon.png
LV_IMG_DECLARE( ui_img_images_png);   // assets/images.png
LV_IMG_DECLARE( ui_img_animals_png);   // assets/animals.png
LV_IMG_DECLARE( ui_img_home_icon_png);   // assets/home_icon.png
LV_IMG_DECLARE( ui_img_plus_icon_png);   // assets/plus_icon.png
LV_IMG_DECLARE( ui_img_back_button_png);   // assets/back_button.png
LV_IMG_DECLARE( ui_img_forward_icon_png);   // assets/forward_icon.png
LV_IMG_DECLARE( ui_img_camera_icon_png);   // assets/camera_icon.png
LV_IMG_DECLARE( ui_img_gallery_icon_png);   // assets/gallery_icon.png
LV_IMG_DECLARE( ui_img_dog_png);   // assets/dog.png
LV_IMG_DECLARE( ui_img_cat_png);   // assets/cat.png
LV_IMG_DECLARE( ui_img_cow_png);   // assets/cow.png
LV_IMG_DECLARE( ui_img_pig_png);   // assets/pig.png
LV_IMG_DECLARE( ui_img_horse_png);   // assets/horse.png
LV_IMG_DECLARE( ui_img_seal_png);   // assets/seal.png
LV_IMG_DECLARE( ui_img_speaker_png);   // assets/speaker.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
