// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    UI_GAME_ANIMAL_DOG = 0,
    UI_GAME_ANIMAL_CAT,
    UI_GAME_ANIMAL_COW,
    UI_GAME_ANIMAL_PIG,
    UI_GAME_ANIMAL_HORSE,
    UI_GAME_ANIMAL_SEAL,
} ui_game_animal_t;

void dark_mode_on(lv_event_t * e);
void dark_mode_off(lv_event_t * e);
void send_msg_gladan(lv_event_t * e);
void send_msg_doma(lv_event_t * e);
void send_msg_skola(lv_event_t * e);
void send_msg_wc(lv_event_t * e);
void start_animal_game_round(lv_event_t * e);
void repeat_animal_sound(lv_event_t * e);
void choose_animal_dog(lv_event_t * e);
void choose_animal_cat(lv_event_t * e);
void choose_animal_cow(lv_event_t * e);
void choose_animal_pig(lv_event_t * e);
void choose_animal_horse(lv_event_t * e);
void choose_animal_seal(lv_event_t * e);
const char *animal_game_get_current_name(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
