// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"
#include "esp_random.h"
#include "esp_log.h"
#include "ui_message_bridge.h"

static const char *TAG = "ui_events";
static ui_game_animal_t s_current_animal = UI_GAME_ANIMAL_DOG;

static ui_animal_sound_t to_bridge_animal(ui_game_animal_t animal)
{
    switch (animal) {
        case UI_GAME_ANIMAL_DOG: return UI_ANIMAL_SOUND_DOG;
        case UI_GAME_ANIMAL_CAT: return UI_ANIMAL_SOUND_CAT;
        case UI_GAME_ANIMAL_COW: return UI_ANIMAL_SOUND_COW;
        case UI_GAME_ANIMAL_PIG: return UI_ANIMAL_SOUND_PIG;
        case UI_GAME_ANIMAL_HORSE: return UI_ANIMAL_SOUND_HORSE;
        case UI_GAME_ANIMAL_SEAL: return UI_ANIMAL_SOUND_SEAL;
        default: return UI_ANIMAL_SOUND_DOG;
    }
}

const char *animal_game_get_current_name(void)
{
    switch (s_current_animal) {
        case UI_GAME_ANIMAL_DOG: return "Pas";
        case UI_GAME_ANIMAL_CAT: return "Macka";
        case UI_GAME_ANIMAL_COW: return "Krava";
        case UI_GAME_ANIMAL_PIG: return "Svinja";
        case UI_GAME_ANIMAL_HORSE: return "Konj";
        case UI_GAME_ANIMAL_SEAL: return "Tuljan";
        default: return "Zivotinja";
    }
}

static void play_current_animal_sound(void)
{
    if (!ui_request_animal_sound(to_bridge_animal(s_current_animal))) {
        ESP_LOGW(TAG, "Animal sound bridge not ready");
    }
}

static void open_animal_result_screen(bool is_correct)
{
    if (is_correct) {
        if (ui_TocanSubtitle) {
            lv_label_set_text_fmt(ui_TocanSubtitle, "To je bio: %s", animal_game_get_current_name());
        }
        _ui_screen_change(&ui_TocanOdgovor, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0,
                          &ui_TocanOdgovor_screen_init);
    } else {
        if (ui_KriviSubtitle) {
            lv_label_set_text_fmt(ui_KriviSubtitle, "Tocno je bilo: %s", animal_game_get_current_name());
        }
        _ui_screen_change(&ui_KriviOdgovor, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0,
                          &ui_KriviOdgovor_screen_init);
    }
}

static void handle_animal_guess(ui_game_animal_t guessed)
{
    open_animal_result_screen(guessed == s_current_animal);
}

static const char *resolve_parent_id(lv_event_t *e)
{
    const char *parent_id = (const char *)lv_event_get_user_data(e);

    if (parent_id != NULL) {
        return parent_id;
    }

    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *screen = target ? lv_obj_get_screen(target) : lv_scr_act();

    if (screen == ui_MamaKontakt) {
        return "Mom";
    }

    if (screen == ui_TataKontakt) {
        return "Dad";
    }

    return NULL;
}

static void send_preset_message(lv_event_t *e, const char *message)
{
    const char *parent_id = resolve_parent_id(e);

    if (parent_id == NULL) {
        ESP_LOGW(TAG, "Cannot resolve parent for event target");
        return;
    }

    if (!ui_send_message_to_parent(parent_id, message)) {
        ESP_LOGW(TAG, "Message bridge not ready for %s", parent_id);
        return;
    }

    ESP_LOGI(TAG, "Sent preset message '%s' to %s", message, parent_id);
}

void dark_mode_on(lv_event_t *e)
{
    lv_color_t bg_color_white = lv_color_hex(0x111111);
    lv_color_t bg_color_black = lv_color_hex(0xFFFFFF);

    lv_obj_add_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_obj_add_state(ui_Dark_Mode_Switch_Color, LV_STATE_CHECKED);
    lv_obj_add_state(ui_Dark_Mode_Switch_Sett, LV_STATE_CHECKED);

    lv_obj_set_style_text_color(ui_Dark_Mode_Label, bg_color_black, 0);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Color, bg_color_black, 0);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, bg_color_black, 0);
    lv_obj_set_style_bg_color(ui_Home_Scr, bg_color_white, 0);
    if (ui_TimeLabel) ui_Home_Scr_refresh_clock();
    if (ui_Alarm_Scr) ui_Alarm_Scr_refresh();
    if (ui_Sketchpad_Scr) ui_Sketchpad_Scr_refresh();
    lv_obj_set_style_bg_color(ui_Color_Scr, bg_color_white, 0);
    lv_obj_set_style_bg_color(ui_Settings_Scr, bg_color_white, 0);
    if (ui_Whats_Down) ui_Whats_Down_refresh();
    if (ui_MamaKontakt) ui_MamaKontakt_refresh();
    if (ui_TataKontakt) ui_TataKontakt_refresh();
    if (ui_PogodiKojaJeZivotinja) ui_PogodiKojaJeZivotinja_refresh();
    if (ui_Zivotinje) ui_Zivotinje_refresh();
    if (ui_TocanOdgovor) ui_TocanOdgovor_refresh();
    if (ui_KriviOdgovor) ui_KriviOdgovor_refresh();
    if (ui_Alarm_Ringing_Scr) ui_Alarm_Ringing_Scr_refresh();
    if (ui_PrimljenePoruke) ui_PrimljenePoruke_refresh();
    if (ui_Camera_Scr) ui_Camera_Scr_refresh();
    if (ui_Gallery_Scr) ui_Gallery_Scr_refresh();

    lv_obj_set_style_bg_color(ui_Settings_scroll_panel, bg_color_white, 0);
    lv_obj_set_style_border_color(ui_Settings_scroll_panel, bg_color_white, 0);
}

void dark_mode_off(lv_event_t *e)
{
    lv_color_t bg_color_white = lv_color_hex(0x111111);
    lv_color_t bg_color_black = lv_color_hex(0xFFFFFF);

    lv_obj_clear_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_obj_clear_state(ui_Dark_Mode_Switch_Color, LV_STATE_CHECKED);
    lv_obj_clear_state(ui_Dark_Mode_Switch_Sett, LV_STATE_CHECKED);

    lv_obj_set_style_text_color(ui_Dark_Mode_Label, bg_color_white, 0);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Color, bg_color_white, 0);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, bg_color_white, 0);
    lv_obj_set_style_bg_color(ui_Home_Scr, bg_color_black, 0);
    if (ui_TimeLabel) ui_Home_Scr_refresh_clock();
    if (ui_Alarm_Scr) ui_Alarm_Scr_refresh();
    if (ui_Sketchpad_Scr) ui_Sketchpad_Scr_refresh();
    lv_obj_set_style_bg_color(ui_Color_Scr, bg_color_black, 0);
    lv_obj_set_style_bg_color(ui_Settings_Scr, bg_color_black, 0);
    if (ui_Whats_Down) ui_Whats_Down_refresh();
    if (ui_MamaKontakt) ui_MamaKontakt_refresh();
    if (ui_TataKontakt) ui_TataKontakt_refresh();
    if (ui_PogodiKojaJeZivotinja) ui_PogodiKojaJeZivotinja_refresh();
    if (ui_Zivotinje) ui_Zivotinje_refresh();
    if (ui_TocanOdgovor) ui_TocanOdgovor_refresh();
    if (ui_KriviOdgovor) ui_KriviOdgovor_refresh();
    if (ui_Alarm_Ringing_Scr) ui_Alarm_Ringing_Scr_refresh();
    if (ui_PrimljenePoruke) ui_PrimljenePoruke_refresh();
    if (ui_Camera_Scr) ui_Camera_Scr_refresh();
    if (ui_Gallery_Scr) ui_Gallery_Scr_refresh();

    lv_obj_set_style_bg_color(ui_Settings_scroll_panel, bg_color_black, 0);
    lv_obj_set_style_border_color(ui_Settings_scroll_panel, bg_color_black, 0);
}

void send_msg_gladan(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    send_preset_message(e, "Gladan");
}

void send_msg_doma(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    send_preset_message(e, "Doma sam");
}

void send_msg_skola(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    send_preset_message(e, "U skoli sam");
}

void send_msg_wc(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    send_preset_message(e, "Moram na WC");
}

void start_animal_game_round(lv_event_t * e)
{
    if (e != NULL && lv_event_get_code(e) != LV_EVENT_CLICKED) return;

    s_current_animal = (ui_game_animal_t)(esp_random() % 6U);
    play_current_animal_sound();
}

void repeat_animal_sound(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    play_current_animal_sound();
}

void choose_animal_dog(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    handle_animal_guess(UI_GAME_ANIMAL_DOG);
}

void choose_animal_cat(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    handle_animal_guess(UI_GAME_ANIMAL_CAT);
}

void choose_animal_cow(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    handle_animal_guess(UI_GAME_ANIMAL_COW);
}

void choose_animal_pig(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    handle_animal_guess(UI_GAME_ANIMAL_PIG);
}

void choose_animal_horse(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    handle_animal_guess(UI_GAME_ANIMAL_HORSE);
}

void choose_animal_seal(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    handle_animal_guess(UI_GAME_ANIMAL_SEAL);
}
