// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"
#include <time.h>

lv_obj_t *ui_Home_Scr = NULL;lv_obj_t *ui_Color_Btn_Home = NULL;lv_obj_t *ui_Colorwheel_Home = NULL;lv_obj_t *ui_BL_logo_Home = NULL;lv_obj_t *ui_Dark_Mode_Label = NULL;lv_obj_t *ui_Dark_Mode_Switch = NULL;lv_obj_t *ui_Settings_Btn_Home = NULL;lv_obj_t *ui_Settings_Icon_Home = NULL;lv_obj_t *ui_WhatsDown = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Alarm = NULL;lv_obj_t *ui_ImageAlarm = NULL;lv_obj_t *ui_Sketchpad = NULL;lv_obj_t *ui_ImageSketchpad = NULL;lv_obj_t *ui_Animals = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Camera = NULL;lv_obj_t *ui_ImageCamera = NULL;lv_obj_t *ui_Gallery = NULL;lv_obj_t *ui_ImageGallery = NULL;lv_obj_t *ui_TimeLabel = NULL;
static lv_timer_t *ui_HomeClockTimer = NULL;

static void ui_HomeClock_timer_cb(lv_timer_t *timer) {
    (void)timer;
    ui_Home_Scr_refresh_clock();
}

void ui_Home_Scr_refresh_clock(void)
{
    time_t now;
    struct tm timeinfo;
    char time_buf[6];
    bool is_dark = ui_Dark_Mode_Switch && lv_obj_has_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);

    if (ui_TimeLabel == NULL) return;

    time(&now);
    localtime_r(&now, &timeinfo);
    strftime(time_buf, sizeof(time_buf), "%H:%M", &timeinfo);
    lv_label_set_text(ui_TimeLabel, time_buf);
    lv_obj_set_style_text_color(ui_TimeLabel, is_dark ? lv_color_hex(0xFFFFFF) : lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
}
// event funtions
void ui_event_Color_Btn_Home( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Color_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Color_Scr_screen_init);
}
}

void ui_event_Dark_Mode_Switch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      dark_mode_on( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      dark_mode_off( e );
}
}

void ui_event_Settings_Btn_Home( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Settings_Scr_screen_init);
}
}

void ui_event_WhatsDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Whats_Down, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Whats_Down_screen_init);
}
}

void ui_event_Animals( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      start_animal_game_round( e );
      _ui_screen_change( &ui_PogodiKojaJeZivotinja, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PogodiKojaJeZivotinja_screen_init);
}
}

void ui_event_Alarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Alarm_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_Alarm_Scr_screen_init);
}
}

void ui_event_Sketchpad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Sketchpad_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_Sketchpad_Scr_screen_init);
}
}

void ui_event_Camera( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      // Re-init if screen was destroyed or failed to init previously
      if (ui_Camera_Scr == NULL) {
          ui_Camera_Scr_screen_init();
      }
      if (ui_Camera_Scr != NULL) {
          _ui_screen_change( &ui_Camera_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_Camera_Scr_screen_init);
      }
}
}

void ui_event_Gallery( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      if (ui_Gallery_Scr != NULL) {
          ui_Gallery_Scr_screen_destroy();
      }
      ui_Gallery_Scr_screen_init();
      if (ui_Gallery_Scr != NULL) {
          _ui_screen_change( &ui_Gallery_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_Gallery_Scr_screen_init);
      }
}
}

// build funtions

void ui_Home_Scr_screen_init(void)
{
ui_Home_Scr = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Home_Scr, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Home_Scr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Color_Btn_Home = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_Color_Btn_Home, 36);
lv_obj_set_height( ui_Color_Btn_Home, 36);
lv_obj_set_x( ui_Color_Btn_Home, 88 );
lv_obj_set_y( ui_Color_Btn_Home, 68 );
lv_obj_set_align( ui_Color_Btn_Home, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Color_Btn_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Color_Btn_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Color_Btn_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Color_Btn_Home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Colorwheel_Home = lv_img_create(ui_Color_Btn_Home);
lv_img_set_src(ui_Colorwheel_Home, &ui_img_colorwheel_icon_png);
lv_obj_set_width( ui_Colorwheel_Home, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Colorwheel_Home, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Colorwheel_Home, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Colorwheel_Home, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Colorwheel_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Colorwheel_Home,75);

ui_BL_logo_Home = lv_img_create(ui_Home_Scr);
lv_img_set_src(ui_BL_logo_Home, &ui_img_bl_logo_symbol_png);
lv_obj_set_width( ui_BL_logo_Home, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BL_logo_Home, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BL_logo_Home, 139 );
lv_obj_set_y( ui_BL_logo_Home, -101 );
lv_obj_set_align( ui_BL_logo_Home, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BL_logo_Home, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BL_logo_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BL_logo_Home,50);

ui_Dark_Mode_Label = lv_label_create(ui_Home_Scr);
lv_obj_set_width( ui_Dark_Mode_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Dark_Mode_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dark_Mode_Label, 76 );
lv_obj_set_y( ui_Dark_Mode_Label, 107 );
lv_obj_set_align( ui_Dark_Mode_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Dark_Mode_Label,"Dark mode");
lv_obj_set_style_text_color(ui_Dark_Mode_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dark_Mode_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Dark_Mode_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_Dark_Mode_Label, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Dark_Mode_Switch = lv_switch_create(ui_Home_Scr);
lv_obj_set_width( ui_Dark_Mode_Switch, 32);
lv_obj_set_height( ui_Dark_Mode_Switch, 15);
lv_obj_set_x( ui_Dark_Mode_Switch, 139 );
lv_obj_set_y( ui_Dark_Mode_Switch, 107 );
lv_obj_set_align( ui_Dark_Mode_Switch, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Dark_Mode_Switch, LV_STATE_CHECKED );     /// States

lv_obj_set_style_bg_color(ui_Dark_Mode_Switch, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Dark_Mode_Switch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_Settings_Btn_Home = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_Settings_Btn_Home, 36);
lv_obj_set_height( ui_Settings_Btn_Home, 36);
lv_obj_set_x( ui_Settings_Btn_Home, 128 );
lv_obj_set_y( ui_Settings_Btn_Home, 68 );
lv_obj_set_align( ui_Settings_Btn_Home, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Btn_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Btn_Home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Icon_Home = lv_img_create(ui_Settings_Btn_Home);
lv_img_set_src(ui_Settings_Icon_Home, &ui_img_settings_icon_png);
lv_obj_set_width( ui_Settings_Icon_Home, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Icon_Home, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Settings_Icon_Home, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Icon_Home, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Icon_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Settings_Icon_Home,75);
lv_obj_set_style_bg_color(ui_Settings_Icon_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Icon_Home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WhatsDown = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_WhatsDown, 88);
lv_obj_set_height( ui_WhatsDown, 88);
lv_obj_set_x( ui_WhatsDown, -118 );
lv_obj_set_y( ui_WhatsDown, -81 );
lv_obj_set_align( ui_WhatsDown, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_WhatsDown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_WhatsDown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_WhatsDown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_WhatsDown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_WhatsDown);
lv_img_set_src(ui_Image2, &ui_img_images_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, -1 );
lv_obj_set_y( ui_Image2, 0 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,230);

ui_Alarm = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_Alarm, 88);
lv_obj_set_height( ui_Alarm, 88);
lv_obj_set_x( ui_Alarm, -118 );
lv_obj_set_y( ui_Alarm, 5 );
lv_obj_set_align( ui_Alarm, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_Alarm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Alarm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Alarm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Alarm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageAlarm = lv_img_create(ui_Alarm);
lv_img_set_src(ui_ImageAlarm, &ui_img_alarm_icon_png);
lv_obj_set_width( ui_ImageAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageAlarm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageAlarm, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageAlarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageAlarm,230);

ui_Sketchpad = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_Sketchpad, 88);
lv_obj_set_height( ui_Sketchpad, 88);
lv_obj_set_x( ui_Sketchpad, -46 );
lv_obj_set_y( ui_Sketchpad, 5 );
lv_obj_set_align( ui_Sketchpad, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_Sketchpad, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Sketchpad, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Sketchpad, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Sketchpad, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageSketchpad = lv_img_create(ui_Sketchpad);
lv_img_set_src(ui_ImageSketchpad, &ui_img_sketchpad_icon_png);
lv_obj_set_width( ui_ImageSketchpad, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageSketchpad, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageSketchpad, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageSketchpad, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageSketchpad, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageSketchpad,230);

ui_Animals = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_Animals, 88);
lv_obj_set_height( ui_Animals, 88);
lv_obj_set_x( ui_Animals, -46 );
lv_obj_set_y( ui_Animals, -79 );
lv_obj_set_align( ui_Animals, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_Animals, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Animals, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Animals, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Animals, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Animals);
lv_img_set_src(ui_Image3, &ui_img_animals_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,230);

ui_Camera = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_Camera, 88);
lv_obj_set_height( ui_Camera, 88);
lv_obj_set_x( ui_Camera, 26 );
lv_obj_set_y( ui_Camera, -79 );
lv_obj_set_align( ui_Camera, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_Camera, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Camera, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Camera, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Camera, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageCamera = lv_img_create(ui_Camera);
lv_img_set_src(ui_ImageCamera, &ui_img_camera_icon_png);
lv_obj_set_width( ui_ImageCamera, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageCamera, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageCamera, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageCamera, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageCamera, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageCamera,230);

ui_Gallery = lv_btn_create(ui_Home_Scr);
lv_obj_set_width( ui_Gallery, 88);
lv_obj_set_height( ui_Gallery, 88);
lv_obj_set_x( ui_Gallery, 98 );
lv_obj_set_y( ui_Gallery, -79 );
lv_obj_set_align( ui_Gallery, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_Gallery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Gallery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Gallery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Gallery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageGallery = lv_img_create(ui_Gallery);
lv_img_set_src(ui_ImageGallery, &ui_img_gallery_icon_png);
lv_obj_set_width( ui_ImageGallery, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageGallery, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageGallery, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageGallery, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageGallery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageGallery,230);

ui_TimeLabel = lv_label_create(ui_Home_Scr);
lv_obj_set_width( ui_TimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeLabel, 10 );
lv_obj_set_y( ui_TimeLabel, -8 );
lv_obj_set_align( ui_TimeLabel, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TimeLabel,"--:--");
lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Color_Btn_Home, ui_event_Color_Btn_Home, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Dark_Mode_Switch, ui_event_Dark_Mode_Switch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Btn_Home, ui_event_Settings_Btn_Home, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WhatsDown, ui_event_WhatsDown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Sketchpad, ui_event_Sketchpad, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Animals, ui_event_Animals, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Camera, ui_event_Camera, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Gallery, ui_event_Gallery, LV_EVENT_ALL, NULL);
ui_Home_Scr_refresh_clock();
ui_HomeClockTimer = lv_timer_create(ui_HomeClock_timer_cb, 1000, NULL);

}

void ui_Home_Scr_screen_destroy(void)
{
   if (ui_HomeClockTimer) {
      lv_timer_del(ui_HomeClockTimer);
      ui_HomeClockTimer = NULL;
   }
   if (ui_Home_Scr) lv_obj_del(ui_Home_Scr);

// NULL screen variables
ui_Home_Scr= NULL;
ui_Color_Btn_Home= NULL;
ui_Colorwheel_Home= NULL;
ui_BL_logo_Home= NULL;
ui_Dark_Mode_Label= NULL;
ui_Dark_Mode_Switch= NULL;
ui_Settings_Btn_Home= NULL;
ui_Settings_Icon_Home= NULL;
ui_WhatsDown= NULL;
ui_Image2= NULL;
ui_Alarm= NULL;
ui_ImageAlarm= NULL;
ui_Sketchpad= NULL;
ui_ImageSketchpad= NULL;
ui_Animals= NULL;
ui_Image3= NULL;
ui_Camera= NULL;
ui_ImageCamera= NULL;
ui_Gallery= NULL;
ui_ImageGallery= NULL;
ui_TimeLabel= NULL;

}
