// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_HOME_SCR_H
#define UI_HOME_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Scr
extern void ui_Home_Scr_screen_init(void);
extern void ui_Home_Scr_screen_destroy(void);
extern void ui_Home_Scr_refresh_clock(void);
extern lv_obj_t *ui_Home_Scr;
extern void ui_event_Color_Btn_Home( lv_event_t * e);
extern lv_obj_t *ui_Color_Btn_Home;
extern lv_obj_t *ui_Colorwheel_Home;
extern lv_obj_t *ui_BL_logo_Home;
extern lv_obj_t *ui_Dark_Mode_Label;
extern void ui_event_Dark_Mode_Switch( lv_event_t * e);
extern lv_obj_t *ui_Dark_Mode_Switch;
extern void ui_event_Settings_Btn_Home( lv_event_t * e);
extern lv_obj_t *ui_Settings_Btn_Home;
extern lv_obj_t *ui_Settings_Icon_Home;
extern void ui_event_WhatsDown( lv_event_t * e);
extern lv_obj_t *ui_WhatsDown;
extern lv_obj_t *ui_Image2;
extern void ui_event_Alarm( lv_event_t * e);
extern lv_obj_t *ui_Alarm;
extern lv_obj_t *ui_ImageAlarm;
extern void ui_event_Sketchpad( lv_event_t * e);
extern lv_obj_t *ui_Sketchpad;
extern lv_obj_t *ui_ImageSketchpad;
extern void ui_event_Animals( lv_event_t * e);
extern lv_obj_t *ui_Animals;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Camera;
extern lv_obj_t *ui_ImageCamera;
extern lv_obj_t *ui_Gallery;
extern lv_obj_t *ui_ImageGallery;
extern lv_obj_t *ui_TimeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
