// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_MAMAKONTAKT_H
#define UI_MAMAKONTAKT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MamaKontakt
extern void ui_MamaKontakt_screen_init(void);
extern void ui_MamaKontakt_screen_destroy(void);
extern void ui_MamaKontakt_refresh(void);
extern lv_obj_t *ui_MamaKontakt;
extern void ui_event_Back( lv_event_t * e);
extern lv_obj_t *ui_Back;
extern void ui_event_Image6( lv_event_t * e);
extern lv_obj_t *ui_Image6;
extern void ui_event_Gladan( lv_event_t * e);
extern lv_obj_t *ui_Gladan;
extern lv_obj_t *ui_Label2;
extern void ui_event_Doma( lv_event_t * e);
extern lv_obj_t *ui_Doma;
extern lv_obj_t *ui_Label1;
extern void ui_event_Skola( lv_event_t * e);
extern lv_obj_t *ui_Skola;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_DodatnaPoruka;
extern lv_obj_t *ui_Image7;
// CUSTOM VARIABLES
extern lv_obj_t *uic_MamaKontakt;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
