// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t *uic_MamaKontakt;
lv_obj_t *ui_MamaKontakt = NULL;lv_obj_t *ui_Back = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Gladan = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Doma = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Skola = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_DodatnaPoruka = NULL;lv_obj_t *ui_Image7 = NULL;

void ui_MamaKontakt_refresh(void)
{
    bool is_dark = ui_Dark_Mode_Switch && lv_obj_has_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_color_t screen_bg = is_dark ? lv_color_hex(0x111111) : lv_color_hex(0xFFF7F0);
    lv_color_t button_bg = is_dark ? lv_color_hex(0x2A2A2A) : lv_color_hex(0xEBA678);
    lv_color_t text_color = is_dark ? lv_color_hex(0xFFFFFF) : lv_color_hex(0x111111);

    if (!ui_MamaKontakt) {
        return;
    }

    lv_obj_set_style_bg_color(ui_MamaKontakt, screen_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MamaKontakt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (ui_Gladan) lv_obj_set_style_bg_color(ui_Gladan, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Doma) lv_obj_set_style_bg_color(ui_Doma, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Skola) lv_obj_set_style_bg_color(ui_Skola, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_DodatnaPoruka) lv_obj_set_style_bg_color(ui_DodatnaPoruka, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (ui_Label2) lv_obj_set_style_text_color(ui_Label2, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Label1) lv_obj_set_style_text_color(ui_Label1, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Label3) lv_obj_set_style_text_color(ui_Label3, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Image7) lv_obj_set_style_text_color(ui_Image7, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
}
// event funtions
void ui_event_Back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Whats_Down, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Whats_Down_screen_init);
}
}

void ui_event_Image6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Whats_Down, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Whats_Down_screen_init);
}
}

void ui_event_Gladan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      send_msg_gladan( e );
}
}

void ui_event_Doma( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      send_msg_doma( e );
}
}

void ui_event_Skola( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      send_msg_skola( e );
}
}

// build funtions

void ui_MamaKontakt_screen_init(void)
{
ui_MamaKontakt = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MamaKontakt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Back = lv_btn_create(ui_MamaKontakt);
lv_obj_set_width( ui_Back, 48);
lv_obj_set_height( ui_Back, 40);
lv_obj_set_x( ui_Back, -127 );
lv_obj_set_y( ui_Back, -91 );
lv_obj_set_align( ui_Back, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Back, lv_color_hex(0xEBA678), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Back, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Back, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Back, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Back, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_Back);
lv_img_set_src(ui_Image6, &ui_img_back_button_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image6,110);

ui_Gladan = lv_btn_create(ui_MamaKontakt);
lv_obj_set_width( ui_Gladan, 100);
lv_obj_set_height( ui_Gladan, 50);
lv_obj_set_x( ui_Gladan, -91 );
lv_obj_set_y( ui_Gladan, -23 );
lv_obj_set_align( ui_Gladan, LV_ALIGN_CENTER );

ui_Label2 = lv_label_create(ui_Gladan);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Gladan");

ui_Doma = lv_btn_create(ui_MamaKontakt);
lv_obj_set_width( ui_Doma, 100);
lv_obj_set_height( ui_Doma, 50);
lv_obj_set_x( ui_Doma, 43 );
lv_obj_set_y( ui_Doma, -21 );
lv_obj_set_align( ui_Doma, LV_ALIGN_CENTER );

ui_Label1 = lv_label_create(ui_Doma);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Doma sam");

ui_Skola = lv_btn_create(ui_MamaKontakt);
lv_obj_set_width( ui_Skola, 100);
lv_obj_set_height( ui_Skola, 50);
lv_obj_set_x( ui_Skola, -87 );
lv_obj_set_y( ui_Skola, 57 );
lv_obj_set_align( ui_Skola, LV_ALIGN_CENTER );

ui_Label3 = lv_label_create(ui_Skola);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"U skoli sam");

ui_DodatnaPoruka = lv_btn_create(ui_MamaKontakt);
lv_obj_set_width( ui_DodatnaPoruka, 100);
lv_obj_set_height( ui_DodatnaPoruka, 50);
lv_obj_set_x( ui_DodatnaPoruka, 48 );
lv_obj_set_y( ui_DodatnaPoruka, 59 );
lv_obj_set_align( ui_DodatnaPoruka, LV_ALIGN_CENTER );

ui_Image7 = lv_label_create(ui_DodatnaPoruka);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_label_set_text(ui_Image7,"Moram na WC");

lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Back, ui_event_Back, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Gladan, ui_event_Gladan, LV_EVENT_ALL, "Mom");
lv_obj_add_event_cb(ui_Doma, ui_event_Doma, LV_EVENT_ALL, "Mom");
lv_obj_add_event_cb(ui_Skola, ui_event_Skola, LV_EVENT_ALL, "Mom");
lv_obj_add_event_cb(ui_DodatnaPoruka, send_msg_wc, LV_EVENT_ALL, "Mom");
uic_MamaKontakt = ui_MamaKontakt;
ui_MamaKontakt_refresh();

}

void ui_MamaKontakt_screen_destroy(void)
{
   if (ui_MamaKontakt) lv_obj_del(ui_MamaKontakt);

// NULL screen variables
uic_MamaKontakt= NULL;
ui_MamaKontakt= NULL;
ui_Back= NULL;
ui_Image6= NULL;
ui_Gladan= NULL;
ui_Label2= NULL;
ui_Doma= NULL;
ui_Label1= NULL;
ui_Skola= NULL;
ui_Label3= NULL;
ui_DodatnaPoruka= NULL;
ui_Image7= NULL;

}
