// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t *ui_PogodiKojaJeZivotinja = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Speaker = NULL;lv_obj_t *ui_Image15 = NULL;lv_obj_t *ui_Next = NULL;lv_obj_t *ui_Image16 = NULL;

void ui_PogodiKojaJeZivotinja_refresh(void)
{
    bool is_dark = ui_Dark_Mode_Switch && lv_obj_has_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_color_t screen_bg = is_dark ? lv_color_hex(0x111111) : lv_color_hex(0xFFF7F0);
    lv_color_t text_color = is_dark ? lv_color_hex(0xFFFFFF) : lv_color_hex(0x111111);
    lv_color_t speaker_bg = is_dark ? lv_color_hex(0x2A2A2A) : lv_color_hex(0xEBA678);

    if (!ui_PogodiKojaJeZivotinja) {
        return;
    }

    lv_obj_set_style_bg_color(ui_PogodiKojaJeZivotinja, screen_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PogodiKojaJeZivotinja, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (ui_Label7) {
        lv_obj_set_style_text_color(ui_Label7, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (ui_Speaker) {
        lv_obj_set_style_bg_color(ui_Speaker, speaker_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_Speaker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_opa(ui_Speaker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_opa(ui_Speaker, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
// event funtions
void ui_event_Speaker( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      repeat_animal_sound( e );
}
}

void ui_event_Next( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Zivotinje, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Zivotinje_screen_init);
}
}

// build funtions

void ui_PogodiKojaJeZivotinja_screen_init(void)
{
ui_PogodiKojaJeZivotinja = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PogodiKojaJeZivotinja, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_PogodiKojaJeZivotinja);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -1 );
lv_obj_set_y( ui_Label7, -86 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Pogodi koja zivotinja se ovako glasa");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speaker = lv_btn_create(ui_PogodiKojaJeZivotinja);
lv_obj_set_width( ui_Speaker, 128);
lv_obj_set_height( ui_Speaker, 128);
lv_obj_set_x( ui_Speaker, -1 );
lv_obj_set_y( ui_Speaker, 12 );
lv_obj_set_align( ui_Speaker, LV_ALIGN_CENTER );

ui_Image15 = lv_img_create(ui_Speaker);
lv_img_set_src(ui_Image15, &ui_img_speaker_png);
lv_obj_set_width( ui_Image15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image15, 0 );
lv_obj_set_y( ui_Image15, -1 );
lv_obj_set_align( ui_Image15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image15, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image15,180);

ui_Next = lv_btn_create(ui_PogodiKojaJeZivotinja);
lv_obj_set_width( ui_Next, 40);
lv_obj_set_height( ui_Next, 30);
lv_obj_set_x( ui_Next, 121 );
lv_obj_set_y( ui_Next, 92 );
lv_obj_set_align( ui_Next, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image16 = lv_img_create(ui_Next);
lv_img_set_src(ui_Image16, &ui_img_forward_icon_png);
lv_obj_set_width( ui_Image16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image16, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image16, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image16,110);

lv_obj_add_event_cb(ui_Speaker, ui_event_Speaker, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Next, ui_event_Next, LV_EVENT_ALL, NULL);
ui_PogodiKojaJeZivotinja_refresh();

}

void ui_PogodiKojaJeZivotinja_screen_destroy(void)
{
   if (ui_PogodiKojaJeZivotinja) lv_obj_del(ui_PogodiKojaJeZivotinja);

// NULL screen variables
ui_PogodiKojaJeZivotinja= NULL;
ui_Label7= NULL;
ui_Speaker= NULL;
ui_Image15= NULL;
ui_Next= NULL;
ui_Image16= NULL;

}
