// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_POGODIKOJAJEZIVOTINJA_H
#define UI_POGODIKOJAJEZIVOTINJA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PogodiKojaJeZivotinja
extern void ui_PogodiKojaJeZivotinja_screen_init(void);
extern void ui_PogodiKojaJeZivotinja_screen_destroy(void);
extern void ui_PogodiKojaJeZivotinja_refresh(void);
extern lv_obj_t *ui_PogodiKojaJeZivotinja;
extern lv_obj_t *ui_Label7;
extern void ui_event_Speaker( lv_event_t * e);
extern lv_obj_t *ui_Speaker;
extern lv_obj_t *ui_Image15;
extern void ui_event_Next( lv_event_t * e);
extern lv_obj_t *ui_Next;
extern lv_obj_t *ui_Image16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
