// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t *uic_TataKontakt;
lv_obj_t *ui_TataKontakt = NULL;lv_obj_t *ui_HomeButton1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Gladan4 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Gladan5 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Gladan6 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Gladan7 = NULL;lv_obj_t *ui_Image8 = NULL;

void ui_TataKontakt_refresh(void)
{
    bool is_dark = ui_Dark_Mode_Switch && lv_obj_has_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_color_t screen_bg = is_dark ? lv_color_hex(0x111111) : lv_color_hex(0xFFF7F0);
    lv_color_t button_bg = is_dark ? lv_color_hex(0x2A2A2A) : lv_color_hex(0xEBA678);
    lv_color_t text_color = is_dark ? lv_color_hex(0xFFFFFF) : lv_color_hex(0x111111);

    if (!ui_TataKontakt) {
        return;
    }

    lv_obj_set_style_bg_color(ui_TataKontakt, screen_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TataKontakt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (ui_Gladan4) lv_obj_set_style_bg_color(ui_Gladan4, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Gladan5) lv_obj_set_style_bg_color(ui_Gladan5, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Gladan6) lv_obj_set_style_bg_color(ui_Gladan6, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Gladan7) lv_obj_set_style_bg_color(ui_Gladan7, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (ui_Label4) lv_obj_set_style_text_color(ui_Label4, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Label5) lv_obj_set_style_text_color(ui_Label5, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Label6) lv_obj_set_style_text_color(ui_Label6, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    if (ui_Image8) lv_obj_set_style_text_color(ui_Image8, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
}
// event funtions
void ui_event_HomeButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Whats_Down, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Whats_Down_screen_init);
}
}

void ui_event_Image1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Whats_Down, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Whats_Down_screen_init);
}
}

// build funtions

void ui_TataKontakt_screen_init(void)
{
ui_TataKontakt = lv_obj_create(NULL);
lv_obj_clear_flag( ui_TataKontakt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton1 = lv_btn_create(ui_TataKontakt);
lv_obj_set_width( ui_HomeButton1, 48);
lv_obj_set_height( ui_HomeButton1, 40);
lv_obj_set_x( ui_HomeButton1, -127 );
lv_obj_set_y( ui_HomeButton1, -91 );
lv_obj_set_align( ui_HomeButton1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_HomeButton1, lv_color_hex(0xEBA678), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_HomeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_HomeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_HomeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_HomeButton1);
lv_img_set_src(ui_Image1, &ui_img_back_button_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,110);

ui_Gladan4 = lv_btn_create(ui_TataKontakt);
lv_obj_set_width( ui_Gladan4, 100);
lv_obj_set_height( ui_Gladan4, 50);
lv_obj_set_x( ui_Gladan4, -91 );
lv_obj_set_y( ui_Gladan4, -23 );
lv_obj_set_align( ui_Gladan4, LV_ALIGN_CENTER );

ui_Label4 = lv_label_create(ui_Gladan4);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Gladan");

ui_Gladan5 = lv_btn_create(ui_TataKontakt);
lv_obj_set_width( ui_Gladan5, 100);
lv_obj_set_height( ui_Gladan5, 50);
lv_obj_set_x( ui_Gladan5, 43 );
lv_obj_set_y( ui_Gladan5, -21 );
lv_obj_set_align( ui_Gladan5, LV_ALIGN_CENTER );

ui_Label5 = lv_label_create(ui_Gladan5);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Doma sam");

ui_Gladan6 = lv_btn_create(ui_TataKontakt);
lv_obj_set_width( ui_Gladan6, 100);
lv_obj_set_height( ui_Gladan6, 50);
lv_obj_set_x( ui_Gladan6, -87 );
lv_obj_set_y( ui_Gladan6, 57 );
lv_obj_set_align( ui_Gladan6, LV_ALIGN_CENTER );

ui_Label6 = lv_label_create(ui_Gladan6);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"U skoli sam");

ui_Gladan7 = lv_btn_create(ui_TataKontakt);
lv_obj_set_width( ui_Gladan7, 100);
lv_obj_set_height( ui_Gladan7, 50);
lv_obj_set_x( ui_Gladan7, 48 );
lv_obj_set_y( ui_Gladan7, 59 );
lv_obj_set_align( ui_Gladan7, LV_ALIGN_CENTER );

ui_Image8 = lv_label_create(ui_Gladan7);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_label_set_text(ui_Image8,"Moram na WC");

lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Gladan4, send_msg_gladan, LV_EVENT_ALL, "Dad");
lv_obj_add_event_cb(ui_Gladan5, send_msg_doma, LV_EVENT_ALL, "Dad");
lv_obj_add_event_cb(ui_Gladan6, send_msg_skola, LV_EVENT_ALL, "Dad");
lv_obj_add_event_cb(ui_Gladan7, send_msg_wc, LV_EVENT_ALL, "Dad");
uic_TataKontakt = ui_TataKontakt;
ui_TataKontakt_refresh();

}

void ui_TataKontakt_screen_destroy(void)
{
   if (ui_TataKontakt) lv_obj_del(ui_TataKontakt);

// NULL screen variables
uic_TataKontakt= NULL;
ui_TataKontakt= NULL;
ui_HomeButton1= NULL;
ui_Image1= NULL;
ui_Gladan4= NULL;
ui_Label4= NULL;
ui_Gladan5= NULL;
ui_Label5= NULL;
ui_Gladan6= NULL;
ui_Label6= NULL;
ui_Gladan7= NULL;
ui_Image8= NULL;

}
