// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_TATAKONTAKT_H
#define UI_TATAKONTAKT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TataKontakt
extern void ui_TataKontakt_screen_init(void);
extern void ui_TataKontakt_screen_destroy(void);
extern void ui_TataKontakt_refresh(void);
extern lv_obj_t *ui_TataKontakt;
extern void ui_event_HomeButton1( lv_event_t * e);
extern lv_obj_t *ui_HomeButton1;
extern void ui_event_Image1( lv_event_t * e);
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Gladan4;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Gladan5;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Gladan6;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Gladan7;
extern lv_obj_t *ui_Image8;
// CUSTOM VARIABLES
extern lv_obj_t *uic_TataKontakt;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
