// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t *uic_KontaktTata1;
lv_obj_t *uic_Button4;
lv_obj_t *uic_Home;
lv_obj_t *uic_Whats_Down;
lv_obj_t *ui_Whats_Down = NULL;lv_obj_t *ui_HomeButton = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_KontaktMama = NULL;lv_obj_t *ui_KontaktTata = NULL;lv_obj_t *ui_KontaktTata1 = NULL;lv_obj_t *ui_Button5 = NULL;lv_obj_t *ui_KontaktMama2 = NULL;lv_obj_t *ui_Image5 = NULL;

static bool ui_Whats_Down_is_dark(void) {
    return ui_Dark_Mode_Switch && lv_obj_has_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
}

void ui_Whats_Down_refresh(void)
{
    bool is_dark = ui_Whats_Down_is_dark();
    lv_color_t screen_bg = is_dark ? lv_color_hex(0x111111) : lv_color_hex(0xFFF7F0);
    lv_color_t button_bg = is_dark ? lv_color_hex(0x2A2A2A) : lv_color_hex(0xEBA678);
    lv_color_t text_color = is_dark ? lv_color_hex(0xF5F5F5) : lv_color_hex(0x000000);

    if (!ui_Whats_Down) {
        return;
    }

    lv_obj_set_style_bg_color(ui_Whats_Down, screen_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Whats_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (ui_HomeButton) {
        lv_obj_set_style_bg_opa(ui_HomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_opa(ui_HomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_opa(ui_HomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_outline_opa(ui_HomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (ui_Button4) {
        lv_obj_set_style_bg_color(ui_Button4, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_Button4, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (ui_KontaktTata) {
        lv_obj_set_style_bg_color(ui_KontaktTata, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_KontaktTata, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (ui_Button5) {
        lv_obj_set_style_bg_color(ui_Button5, button_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_Button5, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (ui_KontaktMama) {
        lv_obj_set_style_text_color(ui_KontaktMama, is_dark ? lv_color_hex(0xFFFFFF) : text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (ui_KontaktTata1) {
        lv_obj_set_style_text_color(ui_KontaktTata1, is_dark ? lv_color_hex(0xFFFFFF) : text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (ui_KontaktMama2) {
        lv_obj_set_style_text_color(ui_KontaktMama2, is_dark ? lv_color_hex(0xFFFFFF) : text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
// event funtions
void ui_event_HomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_Scr_screen_init);
}
}

void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MamaKontakt, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_MamaKontakt_screen_init);
}
}

void ui_event_KontaktTata( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_TataKontakt, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_TataKontakt_screen_init);
}
}

void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ui_PrimljenePoruke_refresh();
      _ui_screen_change( &ui_PrimljenePoruke, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_PrimljenePoruke_screen_init);
}
}

// build funtions

void ui_Whats_Down_screen_init(void)
{
ui_Whats_Down = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Whats_Down, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(ui_Whats_Down, lv_color_hex(0xFFF7F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Whats_Down, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeButton = lv_btn_create(ui_Whats_Down);
lv_obj_set_width( ui_HomeButton, 48);
lv_obj_set_height( ui_HomeButton, 40);
lv_obj_set_x( ui_HomeButton, -127 );
lv_obj_set_y( ui_HomeButton, -91 );
lv_obj_set_align( ui_HomeButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_HomeButton, lv_color_hex(0xEBA678), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_HomeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_HomeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_HomeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_HomeButton);
lv_img_set_src(ui_Image4, &ui_img_back_button_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,110);

ui_Button4 = lv_btn_create(ui_Whats_Down);
lv_obj_set_width( ui_Button4, 58);
lv_obj_set_height( ui_Button4, 54);
lv_obj_set_x( ui_Button4, -109 );
lv_obj_set_y( ui_Button4, 3 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xEBA678), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KontaktMama = lv_label_create(ui_Button4);
lv_obj_set_width( ui_KontaktMama, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_KontaktMama, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_KontaktMama, 0 );
lv_obj_set_y( ui_KontaktMama, 1 );
lv_obj_set_align( ui_KontaktMama, LV_ALIGN_CENTER );
lv_label_set_text(ui_KontaktMama,"Mama");

ui_KontaktTata = lv_btn_create(ui_Whats_Down);
lv_obj_set_width( ui_KontaktTata, 58);
lv_obj_set_height( ui_KontaktTata, 54);
lv_obj_set_x( ui_KontaktTata, -6 );
lv_obj_set_y( ui_KontaktTata, 2 );
lv_obj_set_align( ui_KontaktTata, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_KontaktTata, lv_color_hex(0xEBA678), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_KontaktTata, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_KontaktTata, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_KontaktTata, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KontaktTata1 = lv_label_create(ui_KontaktTata);
lv_obj_set_width( ui_KontaktTata1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_KontaktTata1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_KontaktTata1, 0 );
lv_obj_set_y( ui_KontaktTata1, 1 );
lv_obj_set_align( ui_KontaktTata1, LV_ALIGN_CENTER );
lv_label_set_text(ui_KontaktTata1,"Tata");

ui_Button5 = lv_btn_create(ui_Whats_Down);
lv_obj_set_width( ui_Button5, 58);
lv_obj_set_height( ui_Button5, 54);
lv_obj_set_x( ui_Button5, 99 );
lv_obj_set_y( ui_Button5, 3 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xEBA678), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KontaktMama2 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_KontaktMama2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_KontaktMama2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_KontaktMama2, 0 );
lv_obj_set_y( ui_KontaktMama2, 1 );
lv_obj_set_align( ui_KontaktMama2, LV_ALIGN_CENTER );
lv_label_set_text(ui_KontaktMama2,"Poruke");

ui_Image5 = lv_obj_create(ui_Button5);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_HIDDEN );

lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_KontaktTata, ui_event_KontaktTata, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
uic_Whats_Down = ui_Whats_Down;
uic_Home = ui_HomeButton;
uic_Button4 = ui_Button4;
uic_KontaktTata1 = ui_KontaktTata1;
ui_Whats_Down_refresh();

}

void ui_Whats_Down_screen_destroy(void)
{
   if (ui_Whats_Down) lv_obj_del(ui_Whats_Down);

// NULL screen variables
uic_Whats_Down= NULL;
ui_Whats_Down= NULL;
uic_Home= NULL;
ui_HomeButton= NULL;
ui_Image4= NULL;
uic_Button4= NULL;
ui_Button4= NULL;
ui_KontaktMama= NULL;
ui_KontaktTata= NULL;
uic_KontaktTata1= NULL;
ui_KontaktTata1= NULL;
ui_Button5= NULL;
ui_KontaktMama2= NULL;
ui_Image5= NULL;

}
