// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_WHATS_DOWN_H
#define UI_WHATS_DOWN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Whats_Down
extern void ui_Whats_Down_screen_init(void);
extern void ui_Whats_Down_screen_destroy(void);
extern void ui_Whats_Down_refresh(void);
extern lv_obj_t *ui_Whats_Down;
extern void ui_event_HomeButton( lv_event_t * e);
extern lv_obj_t *ui_HomeButton;
extern lv_obj_t *ui_Image4;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_KontaktMama;
extern void ui_event_KontaktTata( lv_event_t * e);
extern lv_obj_t *ui_KontaktTata;
extern lv_obj_t *ui_KontaktTata1;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_KontaktMama2;
extern lv_obj_t *ui_Image5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Whats_Down;
extern lv_obj_t *uic_Home;
extern lv_obj_t *uic_Button4;
extern lv_obj_t *uic_KontaktTata1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
