// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_ZIVOTINJE_H
#define UI_ZIVOTINJE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Zivotinje
extern void ui_Zivotinje_screen_init(void);
extern void ui_Zivotinje_screen_destroy(void);
extern void ui_Zivotinje_refresh(void);
extern lv_obj_t *ui_Zivotinje;
extern lv_obj_t *ui_Pas;
extern lv_obj_t *ui_Image12;
extern lv_obj_t *ui_Macka;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_Krava;
extern lv_obj_t *ui_Image11;
extern lv_obj_t *ui_Svinja;
extern lv_obj_t *ui_Image14;
extern lv_obj_t *ui_Konj;
extern lv_obj_t *ui_Image13;
extern lv_obj_t *ui_Tuljan;
extern lv_obj_t *ui_Image9;
extern void ui_event_Back2( lv_event_t * e);
extern lv_obj_t *ui_Back2;
extern void ui_event_Image18( lv_event_t * e);
extern lv_obj_t *ui_Image18;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Zivotinje;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
