// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t *uic_Zivotinje;
lv_obj_t *ui_Zivotinje = NULL;lv_obj_t *ui_Pas = NULL;lv_obj_t *ui_Image12 = NULL;lv_obj_t *ui_Macka = NULL;lv_obj_t *ui_Image10 = NULL;lv_obj_t *ui_Krava = NULL;lv_obj_t *ui_Image11 = NULL;lv_obj_t *ui_Svinja = NULL;lv_obj_t *ui_Image14 = NULL;lv_obj_t *ui_Konj = NULL;lv_obj_t *ui_Image13 = NULL;lv_obj_t *ui_Tuljan = NULL;lv_obj_t *ui_Image9 = NULL;lv_obj_t *ui_Back2 = NULL;lv_obj_t *ui_Image18 = NULL;

void ui_Zivotinje_refresh(void)
{
    bool is_dark = ui_Dark_Mode_Switch && lv_obj_has_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);
    lv_color_t screen_bg = is_dark ? lv_color_hex(0x111111) : lv_color_hex(0xFFFFFF);

    if (ui_Zivotinje) {
        lv_obj_set_style_bg_color(ui_Zivotinje, screen_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_Zivotinje, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
// event funtions
void ui_event_Back2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_Scr_screen_init);
}
}

void ui_event_Image18( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Home_Scr_screen_init);
}
}

void ui_event_Pas( lv_event_t * e) {
    choose_animal_dog( e );
}

void ui_event_Macka( lv_event_t * e) {
    choose_animal_cat( e );
}

void ui_event_Krava( lv_event_t * e) {
    choose_animal_cow( e );
}

void ui_event_Svinja( lv_event_t * e) {
    choose_animal_pig( e );
}

void ui_event_Konj( lv_event_t * e) {
    choose_animal_horse( e );
}

void ui_event_Tuljan( lv_event_t * e) {
    choose_animal_seal( e );
}

// build funtions

void ui_Zivotinje_screen_init(void)
{
ui_Zivotinje = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Zivotinje, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_opa(ui_Zivotinje, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pas = lv_btn_create(ui_Zivotinje);
lv_obj_set_width( ui_Pas, 80);
lv_obj_set_height( ui_Pas, 80);
lv_obj_set_x( ui_Pas, -108 );
lv_obj_set_y( ui_Pas, -68 );
lv_obj_set_align( ui_Pas, LV_ALIGN_CENTER );

ui_Image12 = lv_img_create(ui_Pas);
lv_img_set_src(ui_Image12, &ui_img_dog_png);
lv_obj_set_width( ui_Image12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image12,300);

ui_Macka = lv_btn_create(ui_Zivotinje);
lv_obj_set_width( ui_Macka, 80);
lv_obj_set_height( ui_Macka, 80);
lv_obj_set_x( ui_Macka, -3 );
lv_obj_set_y( ui_Macka, -68 );
lv_obj_set_align( ui_Macka, LV_ALIGN_CENTER );

ui_Image10 = lv_img_create(ui_Macka);
lv_img_set_src(ui_Image10, &ui_img_cat_png);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image10,300);

ui_Krava = lv_btn_create(ui_Zivotinje);
lv_obj_set_width( ui_Krava, 80);
lv_obj_set_height( ui_Krava, 80);
lv_obj_set_x( ui_Krava, 99 );
lv_obj_set_y( ui_Krava, -69 );
lv_obj_set_align( ui_Krava, LV_ALIGN_CENTER );

ui_Image11 = lv_img_create(ui_Krava);
lv_img_set_src(ui_Image11, &ui_img_cow_png);
lv_obj_set_width( ui_Image11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image11,300);

ui_Svinja = lv_btn_create(ui_Zivotinje);
lv_obj_set_width( ui_Svinja, 80);
lv_obj_set_height( ui_Svinja, 80);
lv_obj_set_x( ui_Svinja, -107 );
lv_obj_set_y( ui_Svinja, 27 );
lv_obj_set_align( ui_Svinja, LV_ALIGN_CENTER );

ui_Image14 = lv_img_create(ui_Svinja);
lv_img_set_src(ui_Image14, &ui_img_pig_png);
lv_obj_set_width( ui_Image14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image14,300);

ui_Konj = lv_btn_create(ui_Zivotinje);
lv_obj_set_width( ui_Konj, 80);
lv_obj_set_height( ui_Konj, 80);
lv_obj_set_x( ui_Konj, -2 );
lv_obj_set_y( ui_Konj, 27 );
lv_obj_set_align( ui_Konj, LV_ALIGN_CENTER );

ui_Image13 = lv_img_create(ui_Konj);
lv_img_set_src(ui_Image13, &ui_img_horse_png);
lv_obj_set_width( ui_Image13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image13,300);

ui_Tuljan = lv_btn_create(ui_Zivotinje);
lv_obj_set_width( ui_Tuljan, 80);
lv_obj_set_height( ui_Tuljan, 80);
lv_obj_set_x( ui_Tuljan, 100 );
lv_obj_set_y( ui_Tuljan, 26 );
lv_obj_set_align( ui_Tuljan, LV_ALIGN_CENTER );

ui_Image9 = lv_img_create(ui_Tuljan);
lv_img_set_src(ui_Image9, &ui_img_seal_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image9,300);

ui_Back2 = lv_btn_create(ui_Zivotinje);
lv_obj_set_width( ui_Back2, 40);
lv_obj_set_height( ui_Back2, 30);
lv_obj_set_x( ui_Back2, -124 );
lv_obj_set_y( ui_Back2, 92 );
lv_obj_set_align( ui_Back2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_opa(ui_Back2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Back2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_opa(ui_Back2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_opa(ui_Back2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image18 = lv_img_create(ui_Back2);
lv_img_set_src(ui_Image18, &ui_img_back_button_png);
lv_obj_set_width( ui_Image18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image18, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image18, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image18,110);

lv_obj_add_event_cb(ui_Pas, ui_event_Pas, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Macka, ui_event_Macka, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Krava, ui_event_Krava, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Svinja, ui_event_Svinja, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Konj, ui_event_Konj, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Tuljan, ui_event_Tuljan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Image18, ui_event_Image18, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Back2, ui_event_Back2, LV_EVENT_ALL, NULL);
ui_Zivotinje_refresh();
uic_Zivotinje = ui_Zivotinje;

}

void ui_Zivotinje_screen_destroy(void)
{
   if (ui_Zivotinje) lv_obj_del(ui_Zivotinje);

// NULL screen variables
uic_Zivotinje= NULL;
ui_Zivotinje= NULL;
ui_Pas= NULL;
ui_Image12= NULL;
ui_Macka= NULL;
ui_Image10= NULL;
ui_Krava= NULL;
ui_Image11= NULL;
ui_Svinja= NULL;
ui_Image14= NULL;
ui_Konj= NULL;
ui_Image13= NULL;
ui_Tuljan= NULL;
ui_Image9= NULL;
ui_Back2= NULL;
ui_Image18= NULL;

}
