#!/usr/bin/env python3
"""Regenerate compact LVGL image descriptors from UI assets.

This keeps the generated symbol names intact while resizing oversized source
assets to dimensions that make sense for a 240x320 ESP32 UI.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSETS_DIR = ROOT / "components/ui_app/squareline/project/assets"
IMAGES_DIR = ROOT / "components/ui_app/squareline/project/images"


# Match image sizes to the actual on-screen usage. Most are shown inside
# 60x60 or 80x80 buttons with extra LVGL zoom scaling.
TARGET_MAX_EDGE = {
    "alarm_icon.png": 64,
    "animals.png": 128,
    "back_button.png": 64,
    "bl_logo_symbol.png": 128,
    "camera_icon.png": 64,
    "cat.png": 128,
    "colorwheel_icon.png": 128,
    "cow.png": 128,
    "dog.png": 128,
    "forward_icon.png": 64,
    "gallery_icon.png": 64,
    "home_icon.png": 128,
    "horse.png": 128,
    "images.png": 128,
    "pig.png": 128,
    "plus_icon.png": 64,
    "seal.png": 128,
    "sketchpad_icon.png": 64,
    "settings_icon.png": 128,
    "speaker.png": 128,
}


HEADER = """// This file was generated by scripts/regenerate_ui_images.py
// Derived from the original SquareLine asset with a reduced size for ESP32 flash.

#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

"""


def rgb888_to_rgb565_bytes(r: int, g: int, b: int) -> tuple[int, int]:
    value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    # SquareLine project is configured with LV_COLOR_16_SWAP = 1.
    return (value >> 8) & 0xFF, value & 0xFF


def resize_image(path: Path, max_edge: int) -> Image.Image:
    image = Image.open(path).convert("RGBA")
    width, height = image.size
    if max(width, height) <= max_edge:
        return image

    scale = max_edge / float(max(width, height))
    resized = image.resize(
        (max(1, round(width * scale)), max(1, round(height * scale))),
        Image.Resampling.LANCZOS,
    )
    return resized


def image_bytes(image: Image.Image) -> bytes:
    raw = bytearray()
    for r, g, b, a in image.getdata():
        lo, hi = rgb888_to_rgb565_bytes(r, g, b)
        raw.extend((lo, hi, a))
    return bytes(raw)


def emit_c_array(data: bytes) -> str:
    lines = []
    chunk = []
    for index, byte in enumerate(data, start=1):
        chunk.append(f"0x{byte:02X}")
        if len(chunk) == 16 or index == len(data):
            lines.append("    " + ",".join(chunk) + ",")
            chunk = []
    return "\n".join(lines)


def asset_to_symbol(asset_name: str) -> str:
    stem = Path(asset_name).stem
    return f"ui_img_{stem}_png"


def generate_one(asset_path: Path, max_edge: int) -> None:
    symbol = asset_to_symbol(asset_path.name)
    output_path = IMAGES_DIR / f"{symbol}.c"
    image = resize_image(asset_path, max_edge)
    data = image_bytes(image)

    contents = (
        HEADER
        + f"// IMAGE DATA: assets/{asset_path.name}\n"
        + f"const LV_ATTRIBUTE_MEM_ALIGN uint8_t {symbol}_data[] = {{\n"
        + emit_c_array(data)
        + "\n};\n"
        + f"const lv_img_dsc_t {symbol} = {{\n"
        + "   .header.always_zero = 0,\n"
        + f"   .header.w = {image.width},\n"
        + f"   .header.h = {image.height},\n"
        + f"   .data_size = sizeof({symbol}_data),\n"
        + "   .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n"
        + f"   .data = {symbol}_data}};\n"
    )

    output_path.write_text(contents, encoding="utf-8")
    print(f"{asset_path.name}: {image.width}x{image.height} -> {output_path.name}")


def main() -> None:
    for asset_name, max_edge in sorted(TARGET_MAX_EDGE.items()):
        generate_one(ASSETS_DIR / asset_name, max_edge)


if __name__ == "__main__":
    main()
